FROM python:3.9-slim

WORKDIR /app

COPY mdp_metrics.py .

# Install curl for healthcheck
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8080

CMD ["python", "mdp_metrics.py"]
