services:
  # Main Trading Engine
  - type: worker
    name: trading-agent-engine
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python flash_trading.py --mode production
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: PAPER_TRADING
        value: "False"
      - key: BOT_SERVICE_URL
        value: "http://trading-agent-llm-overseer:8000"
  
  # Dashboard Interface
  - type: web
    name: trading-agent-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python mexc_dashboard_production.py
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: ENVIRONMENT
        value: production
      - key: BOT_SERVICE_URL
        value: "http://trading-agent-llm-overseer:8000"
    
  # LLM Overseer with Telegram Bot for LLM-Powered Key Management
  - type: web
    name: trading-agent-llm-overseer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m llm_overseer.telegram.run_llm_powered_bot
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_ALLOWED_USERS
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
