name: Run Telegram Bot

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - master  # Run on pushes to master branch
    paths:
      - 'llm_overseer/telegram/**'  # Only run when telegram bot files change

jobs:
  run-telegram-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 1440  # 24 hours max runtime

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cryptography python-telegram-bot
          pip install -r requirements.txt

      - name: Run Telegram Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_ALLOWED_USERS: ${{ secrets.TELEGRAM_ALLOWED_USERS }}
        run: |
          python -m llm_overseer.telegram.run_llm_powered_bot
